services:
  app:
    build:
      context: ./
      target: builder
      args:
          - USER_ID=${USER_ID:-1000}
          - GROUP_ID=${GROUP_ID:-1000}
    ports:
      - '9090:80'
    volumes:
      - ./:/var/www/html
    networks:
      - caspian

  mariadb:
    image: mariadb:11.4
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ALLOW_EMPTY_PASSWORD=true
      - MARIADB_USER=musicuser
      - MARIADB_PASSWORD=musicpass
      - MARIADB_DATABASE=musicdb
    volumes:
      - "~/docker-volume/muzik/mariadb:/var/lib/mysql"
      # - "./entrypoints/0001.init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - caspian

networks:
  caspian: { }
